version: "3.8"

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD= mysqlpass
     - MYSQL_DATABASE= db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app-foyer:
    depends_on:
      - mysqldb
    image: onshanafi/foyer:5.0.0
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "mysqlpass",
        "spring.jpa.hibernate.ddl-auto" : "update"     
      }'
    stdin_open: true
    tty: true
volumes:
  db :






